const languageNameCodeMap = {
  Arabic: "ar",
  Bulgarian: "bg",
  Bengali: "bn",
  Czech: "cs",
  Danish: "da",
  German: "de",
  Greek: "el",
  English: "en",
  Spanish: "es",
  Estonian: "et",
  Persian: "fa",
  Finnish: "fi",
  French: "fr",
  Hebrew: "he",
  Hindi: "hi",
  Croatian: "hr",
  Hungarian: "hu",
  Indonesian: "id",
  Italian: "it",
  Irish: "ga",
  Japanese: "ja",
  Korean: "ko",
  Lithuanian: "lt",
  Latvian: "lv",
  Malay: "ms",
  "Norwegian Bokmål": "nb",
  Dutch: "nl",
  Polish: "pl",
  "Portuguese (Brazil)": "pt",
  Portuguese: "pt",
  Romanian: "ro",
  Russian: "ru",
  Slovak: "sk",
  Slovenian: "sl",
  Albanian: "sq",
  Serbian: "sr",
  Swedish: "sv",
  Swahili: "sw",
  Thai: "th",
  Turkish: "tr",
  Ukrainian: "uk",
  Urdu: "ur",
  Vietnamese: "vi",
  "Chinese Simplified": "zh-Hans",
};

export default languageNameCodeMap;
